### ISSUE TITLE
problem to use this bundle with php 7.2.24

### ISSUE THREAD

**Issue by celsoandrade** [BedrockStreaming/GuzzleHttpBundle#68]
I'm getting this error after php upgrade.

`Warning: Use of undefined constant CURLOPT_FOLLOWLOCATION - assumed 'CURLOPT_FOLLOWLOCATION' (this will throw an Error in a future version of PHP)`

**Comment by Oliboy50** [comment]
hello 👋

[the documentation](https://www.php.net/manual/en/function.curl-setopt.php) doesn't seem to warn us about this 🤔

**Comment by mojoLyon** [comment]
May be you need to install / enable the curl extension in php.ini ?

**Comment by Oliboy50** [comment]
closing as outdated since php7.2 is not a supported release anymore, feel free to reopen if you still have issues
